###Exp No - 10
##Name -Jai Pratap
##PRN - 25070123056
##ENTC - A3
##Title - Create and load the data set

In [ ]:
# Create a data set
import pandas as pd

data = {
    "Roll_No":[101,102,103,104,105],


   "Gender":["Female","Male","Female","Male","Female"],

    "Department":["Computer","IT","Electrical","Mechanical","Civil"],

    "CGPA":[8.2,7.5,9.1,9.5,8.5]
}

df = pd.DataFrame(data)

df.to_csv("student_data.csv",index=False)

print(df)

   Roll_No  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female  Electrical   9.1
3      104    Male  Mechanical   9.5
4      105  Female       Civil   8.5

In [ ]:
# rows and columns

df.shape

(5, 4)

In [ ]:
#Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
# Size
df.size

20

In [ ]:
# Access information of column department
df["Department"]

0      Computer
1            IT
2    Electrical
3    Mechanical
4         Civil
Name: Department, dtype: object

In [ ]:
# Access information of prn 103
df[df["Roll_No"] == 103]

   Roll_No  Gender  Department  CGPA
2      103  Female  Electrical   9.1

In [ ]:
# Find out data from each column
df.columns

In [ ]:
# Perform mean , median and mode operation

print(df["CGPA"].mean())
print(df["CGPA"].median())
print(df["CGPA"].mode())

In [ ]:
# Insert a new column grade

df["Grade"] = ["A","B","A+","A+","A"]
df

In [ ]:
# Delete Gender column

df = df.drop("Gender", axis=1)
df

In [ ]:
# CGPA of topper
df["CGPA"].max()

9.5

In [ ]:
# CGPA of PRN 105

df["CGPA"][df["Roll_No"] == 105]

4    8.5
Name: CGPA, dtype: float64

In [ ]:
# Upload the data set
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Cars93 (1).csv")
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/Cars93 (1).csv'

In [ ]:
# Size
df.size

In [ ]:
# Information
df.info()

In [ ]:
# Check no of rows and columns

df.shape

In [ ]:
df.headdf.head

In [ ]:
df.tail

In [ ]:
df.describe